In [113]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.model_selection import cross_val_score 

In [114]:
veri = pd.read_csv("breast-cancer-wisconsin.data")
veri.head()

id  clumpthickness  uniformcellsize  uniformcellshape  margadhesion  \
0  1000025               5                1                 1             1   
1  1002945               5                4                 4             5   
2  1015425               3                1                 1             1   
3  1016277               6                8                 8             1   
4  1017023               4                1                 1             3   

   epithelial barenuclei  blandchromatin  normalnucleoli  mitoses  benormal  
0           2          1               3               1        1         2  
1           7         10               3               2        1         2  
2           2          2               3               1        1         2  
3           3          4               3               7        1         2  
4           2          1               3               1        1         2

In [115]:
veri.replace('?', -7777, inplace=True)
veri.head(24)

id  clumpthickness  uniformcellsize  uniformcellshape  margadhesion  \
0   1000025               5                1                 1             1   
1   1002945               5                4                 4             5   
2   1015425               3                1                 1             1   
3   1016277               6                8                 8             1   
4   1017023               4                1                 1             3   
5   1017122               8               10                10             8   
6   1018099               1                1                 1             1   
7   1018561               2                1                 2             1   
8   1033078               2                1                 1             1   
9   1033078               4                2                 1             1   
10  1035283               1                1                 1             1   
11  1036172               2                1                 1             1   
12  1041801               5                3                 3             3   
13  1043999               1                1                 1             1   
14  1044572               8                7                 5            10   
15  1047630               7                4                 6             4   
16  1048672               4                1                 1             1   
17  1049815               4                1                 1             1   
18  1050670              10                7                 7             6   
19  1050718               6                1                 1             1   
20  1054590               7                3                 2            10   
21  1054593              10                5                 5             3   
22  1056784               3                1                 1             1   
23  1057013               8                4                 5             1   

    epithelial barenuclei  blandchromatin  normalnucleoli  mitoses  benormal  
0            2          1               3               1        1         2  
1            7         10               3               2        1         2  
2            2          2               3               1        1         2  
3            3          4               3               7        1         2  
4            2          1               3               1        1         2  
5            7         10               9               7        1         4  
6            2         10               3               1        1         2  
7            2          1               3               1        1         2  
8            2          1               1               1        5         2  
9            2          1               2               1        1         2  
10           1          1               3               1        1         2  
11           2          1               2               1        1         2  
12           2          3               4               4        1         4  
13           2          3               3               1        1         2  
14           7          9               5               5        4         4  
15           6          1               4               3        1         4  
16           2          1               2               1        1         2  
17           2          1               3               1        1         2  
18           4         10               4               1        2         4  
19           2          1               3               1        1         2  
20           5         10               5               4        4         4  
21           6          7               7              10        1         4  
22           2          1               2               1        1         2  
23           2      -7777               7               3        1         4

In [116]:
veri= veri.drop(['id'], axis=1)
veri.head()

clumpthickness  uniformcellsize  uniformcellshape  margadhesion  \
0               5                1                 1             1   
1               5                4                 4             5   
2               3                1                 1             1   
3               6                8                 8             1   
4               4                1                 1             3   

   epithelial barenuclei  blandchromatin  normalnucleoli  mitoses  benormal  
0           2          1               3               1        1         2  
1           7         10               3               2        1         2  
2           2          2               3               1        1         2  
3           3          4               3               7        1         2  
4           2          1               3               1        1         2

In [117]:
y=np.array(veri.benormal)
x=np.array(veri.drop(['benormal'], axis=1))
print("y:")
print(y)

print("\nx:")
print(x)


y:
[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 4 2 4 2 2 2 2 2 2 4 2 2 2 4
 2 4 4 2 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4
 4 2 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2
 4 4 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 4 2
 2 4 2 4 4 2 2 4 2 2 2 4 4 2 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4
 2 4 4 4 2 4 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4
 4 4 4 2 4 4 2 4 4 4 2 4 2 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 2 4 2 4 4 4 2 2 2
 2 4 4 4 4 4 2 4 4 4 2 4 2 4 4 2 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 4
 2 2 2 4 4 2 4 2 4 4 2 2 4 2 2 2 4 2 2 2 4 4 2 2 4 2 2 4 2 2 4 2 4 4 4 2 2
 4 4 2 4 2 2 4 4 2 2 2 4 2 2 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2
 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2
 2 2 2 2 2 4 2 4 2 4 2 2 2 2 4 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2
 2 2 2 2 2 4 2 2 2 4 2 4 4 4 2 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2
 2 4 4 2 2 2 4 4 4 2 4

In [118]:
imp = SimpleImputer(missing_values=-7777, strategy="mean")
x = imp.fit_transform(x)
print(x)
#soru işarerti olan yerlere 777 koymak yerine, 
#o satırın ortalamasını alıyo ki tahminler en az şekilde etkilensin

[[ 5.  1.  1. ...  3.  1.  1.]
 [ 5.  4.  4. ...  3.  2.  1.]
 [ 3.  1.  1. ...  3.  1.  1.]
 ...
 [ 5. 10. 10. ...  8. 10.  2.]
 [ 4.  8.  6. ... 10.  6.  1.]
 [ 4.  8.  8. ... 10.  4.  1.]]


In [119]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33)

In [1]:
#tahmin = KNeighborsClassifier()
#tahmin.fit(x_train,y_train)
#basaria=tahmin.score(x_test,y_test)
#print("yüzde",basaria*100,"oranında")
#a = np.array([2,9,3,5,3,6,1,9,5]).reshape(1,-1)
#print(tahmin.predict(a))
#2= iyi huylu, 4= kötü huylu
#kn e göre sınıflandırma yapıcaz. en yakın 3 komşuya göre değerrlendiriyo
#kaç komşuya göre doğruluk değeri artar

In [2]:
#hangi k değerinin daha iyi sonuç verdiğini görmek için ve tek olması gerek
for z in range(25):
    z = 2*z+1
    print("En yakın",z,"komşu kullandığımızda tutarlılık oranımız:")
    tahmin = KNeighborsClassifier(n_neighbors=z, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='euclidean', metric_params=None, n_jobs=1)
    tahmin.fit(x,y)
    ytahmin = tahmin.predict(x)

    basari = accuracy_score(y, ytahmin, normalize=True, sample_weight=None)
    print(basari)

En yakın 1 komşu kullandığımızda tutarlılık oranımız


NameError: name 'KNeighborsClassifier' is not defined